### ISSUE TITLE
AttributeError: 'module' object has no attribute 'black_scholes'

### ISSUE THREAD

**Issue by romanrdgz** [vollib/vollib#1]
I'm having problems testing the black_scholes method. If I import vollib, no error is thrown, but then it does not seem to find black_scholes method. Also tried vollib.black_scholes.black_scholes.

Might it be related to a bad SWIG installation?
```

import vollib
import numpy as np

underlying_price = np.linspace(180, 205, num=200)
strike_price = 195
interest_rate = 1
days_to_expire = 20
t_years = days_to_expire / 365
iv = 20

y = [vollib.black_scholes(
        'c', x, strike_price, t_years, interest_rate/100, iv)
      for x in underlying_price]
plt.plot(underlying_price, y1, 'b-', label='vollib')
```

Also, I don't know if an interest rate of 1% shall be introduced as 1 or as 0.01, not if the time to expiration shall be days to expiration or days/365.

**Comment by iotatx** [comment]
Try running the doc tests to confirm your installation.   
You are doing integer division to get t in years, which is presumably not what you want.  Either make 365 into 365.  or 20 into 20.   (Casting to float).  Interest rate should be .01 and iv should be .2 rather than 20.   I suggest starting withe the examples in the documentation and modifying them to suit your needs.

**Comment by romanrdgz** [comment]
I finally made it work by correctly installing swig. Nevertheless, I still have doubts about implied volatility. If, for example VIX is around 20% today, I assume that is sigma = IV = 20, not 0.2.

I am currently comparing your library against others to determine which one to use for my project. In this case, if I compare against MibianLib using IV= 20 and IV=0.2 for vollib, I get the same plot.

I am not a volatility expert (I wish!), but it don't understand why are you using iv/100 instead of the iv directly.

Moreover, I was having troubles by not using floats as you suggested in your answer. In this case, when passing iv/100, the value being passed where zero. It took me a while to understand from the plot what was going on. Even being my mistake, maybe it would be useful to ass a warning note when a non float value is being passed.

**Comment by iotatx** [comment]
Roman,

Outside the mainstream quant community you might see it done differently, but Black Scholes implied volatility is expressed, by standard convention, as a fraction rather than a percentage.  This is how it is done in the Black & Scholes original publications.  You will see this consistently in the publications of Black and Scholes, John C. Hull, Corrado and Miller, Paul Wilmott, Espen Haug,  and, of course, Peter Jaeckel.

You will notice that in the doctests I have taken many examples from John C. Hull’s book, “Options, Futures and other Derivatives.”  If you do not have this book, I highly recommend it.

At its core vollib is a wrapper around Peter Jaeckel’s C++ code, I have tried to stay as consistent as possible to his naming conventions and API.

Integer division behavior is part of the python language and not specific to vollib.

—Larry

**Comment by romanrdgz** [comment]
Sure, just saying that if someone passes a zero volatility, most probably is an error. Therefore, printing a warning would not make any harm.

In case you are interested in knowing, these are the results of comparing against MibianLib:
20000 executions with MibianLib: 23.481 seconds
20000 executions with VolLib: 0.054 seconds
200000 executions with MibianLib: 239.423 seconds
200000 executions with VolLib: 0.631 seconds

Quite impressive! I hope it works when I try running in it a Raspberry Pi

**Comment by iotatx** [comment]
Very cool.  I will be interested to learn about the results on a Raspberry Pi.  One of my plans is to add exception handling to Vollib in a future version, so thanks for the suggestion.

**Comment by romanrdgz** [comment]
My current project is running 24/7 a Raspberry Pi connected to Interactive Brokers data feed and detect good oportunities for opening calendar spreads, sending me e-mail alerts with plots. I'm still building the code before migrating to the Pi, but I'm obviously concerned about its performances once migrated. Therefore, your lib looks like a lifesaver.

I'll let you know about future results
