### ISSUE TITLE
Porting to Python 3.

### ISSUE THREAD

**Issue by bstemper** [vollib/vollib#2]

**Comment by iotatx** [comment]
Got it Ben.  The time has come for this.  I also want to do some refactoring of the internals, so I'll add this to the wish list and aim for a not to distant release.  BTW, thank you for sobol_seq - I'm getting good mileage out of this in MC simulation.

**Comment by thejackluo** [comment]
Sounds good! Let me know if you need a hand for porting or testing

**Comment by iotatx** [comment]
Thanks Jack!  I'll plan to reach out to you when the right time comes.

**Comment by romanrdgz** [comment]
Is there any progress on the port to Python 3?

**Comment by iotatx** [comment]
Yes, it’s ported but I want to do some refactoring before making it public.  I’ve put this on the back burner for now because we have other business-critical activities that are higher priority.

FYI, the changes required just for Python 3 compatibility were mostly quite trivial.  If you’re in a hurry you could do this in a local copy quite quickly.

**Comment by romanrdgz** [comment]
That's what I thought at first, so I already tried that. The problem is that I am getting problems with LetsBeRational:

pip install lets_be_rational
Requirement already satisfied: lets_be_rational in c:\users\roman\appdata\local\programs\python\python35-32\lib\site-packages

python test_black_scholes.py          <----- This is one of vollib's tests
File "c:\Users\roman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\lets_be_rational\__init__.py", line 1, in <module>
    from LetsBeRational import black
ImportError: No module named 'LetsBeRational'

Couldn't you provide the python 3 compatible package as an alpha version?

**Comment by iotatx** [comment]
That’s mysterious.  The bottleneck right now (aside from me doing the refactoring) is that my github admin guy is piled up with mission critical jobs.  Our new boss (the fund’s founder and CIO) has a ton of ideas for us to develop which directly impact the fund’s performance, and a vollib upgrade isn’t one of them.  Can’t promise a delivery date, but I will roll something out at first opportunity.

**Comment by romanrdgz** [comment]
I appreciate it

**Comment by jackwluo** [comment]
Vollib itself ports just fine using 2to3; it seems like a swig/lets be rational issue (getting same error)

**Comment by romanrdgz** [comment]
Any updates on this?

**Comment by iotatx** [comment]
Yes!

http://www.gammoncap.com/insights/page/4/gammon-capital-announces-updates-to-vollib/

**Comment by iotatx** [comment]
I'm going to mark this as closed.  With py_vollib I chose to abandon SWIG and C all together.  The SWIG/C wrapper approach is simply too OS dependent.  Since most of my developers use Mac OSX, it would be too much effort (IMO) to create and test a separate SWIG installer script for Windows and Linux.  The pure python py_vollib does not execute as fast as the Python/SWIG/C version (vollib), but it is still nearly two orders of magnitude faster than Newton's method for calculating implied volatility.  Numba (optional) mitigates this and significantly narrows the speed gap between Python and C.  For more info, see my blog post here:  http://www.gammoncap.com/insights/page/4/gammon-capital-announces-updates-to-vollib/
